export const landingPageCopy = {
  brandEyebrow: 'nền tảng nhạc theo cảm xúc',
  enterApp: 'Vào app',
  heroBadge: 'Nhạc theo cảm xúc',
  heroTitle: 'Âm nhạc bắt đầu',
  heroTitleAccent: 'từ cảm xúc của cậu.',
  heroDescription:
    'Nhận diện tâm trạng, hiểu gu nghe và gợi ý đúng lúc trong một không gian nghe nhạc gọn, sang và rất cá nhân.',
  primaryCta: 'Nghe ngay',
  secondaryCta: 'Nhận diện cảm xúc',
  previewEyebrow: 'Xem nhanh trong app',
  previewTitle: 'Phiên nghe đêm nay',
  previewDescription: 'Gợi ý theo cảm xúc ngay trong không gian nghe chính',
  previewStatus: 'Đã đồng bộ cảm xúc',
  previewMoodFit: 'Độ hợp cảm xúc',
  previewCurrentMood: 'Tâm trạng hiện tại',
  previewMoodValue: 'Thư giãn',
  previewMoodDescription: 'App bắt đầu từ cảm xúc, rồi hòa cùng gu nghe và thói quen để chọn bài tiếp theo.',
  previewQueueTitle: 'Hàng chờ trợ lý',
  previewQueueBadge: 'Gợi ý nội bộ',
  previewQueueReasons: ['Chọn theo cảm xúc', 'Hợp gu gần đây', 'Hợp nhịp nghe đêm'],
  openPicks: 'Mở gợi ý',
  explore: 'Khám phá',
  landingSections: {
    emotions: {
      eyebrow: 'Cảm xúc',
      title: 'Khám phá theo cảm xúc',
      description: 'Mood là điểm vào chính của sản phẩm, nên việc khám phá bắt đầu từ cảm xúc thay vì một danh mục vô hồn.',
    },
    genres: {
      eyebrow: 'Thể loại',
      title: 'Khám phá theo thể loại',
      description: 'Cảm xúc là trung tâm, nhưng hành trình nghe vẫn cần thêm chiều rộng để mở ra những hướng hợp gu.',
    },
    howItWorks: {
      eyebrow: 'Cách hoạt động',
      title: 'Cách hoạt động',
      description: 'Giải thích nhanh, gọn và đúng với flow thật của app: đọc cảm xúc, hiểu gu nghe rồi đẩy ra lựa chọn phù hợp.',
    },
    personalization: {
      eyebrow: 'Cá nhân hóa',
      title: 'Xem trước theo gu nghe',
      description: 'Không chỉ phản ứng với mood hiện tại, app còn học từ gu nghe, nghệ sĩ thường mở và nhịp nghe quen thuộc.',
    },
    playlists: {
      eyebrow: 'Tuyển chọn',
      title: 'Playlist nổi bật',
      description: 'Những playlist mang dấu ấn cảm xúc, thói quen nghe và gu nội dung của chính MoodSync AI.',
    },
    premium: {
      eyebrow: 'Premium',
      title: 'Trải nghiệm nâng cấp',
      description: 'Mở khóa phân tích sâu hơn, trợ lý giàu ngữ cảnh hơn và playlist thích ứng mà vẫn giữ giao diện sạch, sang.',
      cta: 'Khám phá Premium',
    },
    final: {
      eyebrow: 'Sẵn sàng nghe',
      title: 'Một không gian nghe nhạc premium, bắt đầu từ cảm xúc.',
      description: 'Vào app, đọc mood và mở ngay flow gợi ý được cá nhân hóa cho cậu.',
      primaryCta: 'Vào app',
      secondaryCta: 'Phân tích cảm xúc',
      tertiaryCta: 'Xem gợi ý',
    },
  },
  productPreviewLabels: {
    currentMood: 'Tâm trạng hiện tại',
    queue: 'Hàng chờ trợ lý',
    internalPicks: 'Gợi ý nội bộ',
  },
  footer: 'Không gian nghe nhạc lấy cảm xúc làm điểm bắt đầu.',
  featuredPlaylistCta: 'Mở',
  songsUnit: 'bài',
  playlistOverrides: {
    pl1: {
      name: 'K-pop vui vẻ',
      description: 'Những bài bắt tai để bật lên khi mood đang sáng.',
    },
    pl2: {
      name: 'Đêm lãng mạn',
      description: 'Gợi ý dành cho lúc muốn nghe nhạc tình cảm và mềm hơn.',
    },
    pl3: {
      name: 'Sau cơn mưa',
      description: 'Nhạc nhẹ cho những lúc chỉ muốn ngồi yên.',
    },
    pl4: {
      name: 'Bùng nổ năng lượng',
      description: 'Nhạc mạnh để nâng nhịp, vận động và bứt tốc.',
    },
    pl5: {
      name: 'Ký ức mùa cũ',
      description: 'Nhạc cho những lúc cần một chút hoài niệm.',
    },
    pl6: {
      name: 'Thư giãn ban đêm',
      description: 'Giai điệu để nghỉ ngơi, thả lỏng và dịu lại.',
    },
  },
} as const

export const dashboardHomeCopy = {
  heroTitle: 'Bắt đầu phiên nghe từ cảm xúc của cậu',
  heroDescription: 'Tâm trạng hiện tại sẽ dẫn lối tới những bài hát và playlist hợp nhất cho phiên này.',
  detectEmotion: 'Nhận diện cảm xúc',
  playNow: 'Phát ngay',
  moodSync: 'Đồng bộ cảm xúc',
  topGenre: 'Thể loại chính',
  peakWindow: 'Khung giờ hợp gu',
  session: {
    eyebrow: 'Dành cho phiên này',
    title: 'Mở ngay một bài để giữ đúng mạch nghe',
    more: 'Xem thêm',
    reasons: [
      'Hợp với cảm xúc hiện tại.',
      'Khớp với gu nghe gần đây.',
      'Được AI ưu tiên cho phiên này.',
      'Bài cậu hay mở lại vào buổi tối.',
    ],
  },
  emotions: {
    eyebrow: 'Khám phá theo cảm xúc',
    title: 'Cậu đang muốn nghe theo trạng thái nào?',
    blocks: [
      { id: 'happy', label: 'Vui vẻ', emoji: '😊', accent: 'from-amber-400/30 via-orange-400/12 to-transparent' },
      { id: 'sad', label: 'Buồn', emoji: '😢', accent: 'from-sky-400/30 via-blue-500/12 to-transparent' },
      { id: 'focus', label: 'Tập trung', emoji: '🎯', accent: 'from-emerald-400/28 via-cyan-400/12 to-transparent' },
      { id: 'healing', label: 'Chữa lành', emoji: '💚', accent: 'from-emerald-400/26 via-lime-300/12 to-transparent' },
      { id: 'relax', label: 'Thư giãn', emoji: '☁️', accent: 'from-cyan-400/28 via-teal-400/12 to-transparent' },
      { id: 'sleep', label: 'Dễ ngủ', emoji: '🌙', accent: 'from-violet-400/28 via-indigo-500/12 to-transparent' },
      { id: 'energetic', label: 'Xả stress', emoji: '🔥', accent: 'from-rose-400/28 via-red-500/12 to-transparent' },
      { id: 'lonely', label: 'Cô đơn', emoji: '🥀', accent: 'from-orange-400/26 via-amber-300/12 to-transparent' },
    ],
  },
  collections: {
    eyebrow: 'Bộ sưu tập cảm xúc',
    title: 'Nghe theo khoảnh khắc',
    items: [
      {
        id: 'cry',
        title: 'Cho lúc muốn khóc',
        subtitle: 'Để mọi cảm xúc trôi ra, rồi lòng nhẹ hơn.',
        emoji: '🥲',
        accent: 'from-blue-400/30 via-indigo-400/12 to-transparent',
        songIds: ['5', '7', '10'],
      },
      {
        id: 'alert',
        title: 'Cho lúc cần tỉnh táo',
        subtitle: 'Beat gọn, nhịp chắc, giữ đầu óc sáng.',
        emoji: '⚡',
        accent: 'from-amber-400/30 via-orange-400/12 to-transparent',
        songIds: ['3', '9', '11'],
      },
      {
        id: 'night-walk',
        title: 'Cho lúc đi đêm',
        subtitle: 'Lofi, ambient và một chút khoảng lặng.',
        emoji: '🌃',
        accent: 'from-violet-400/28 via-purple-400/12 to-transparent',
        songIds: ['10', '2', '4'],
      },
      {
        id: 'calm-down',
        title: 'Cho lúc cần dịu lại',
        subtitle: 'Hạ nhịp, thở chậm và để mood ổn hơn.',
        emoji: '🧘',
        accent: 'from-emerald-400/28 via-teal-400/12 to-transparent',
        songIds: ['10', '8', '2'],
      },
      {
        id: 'soft-happy',
        title: 'Vui nhưng không quá ồn',
        subtitle: 'Sáng nhẹ, đáng yêu và rất dễ nghe lại.',
        emoji: '🌸',
        accent: 'from-pink-400/28 via-rose-300/12 to-transparent',
        songIds: ['6', '8', '11'],
      },
    ],
    songsUnit: 'bài',
  },
  genres: {
    eyebrow: 'Theo thể loại',
    title: 'Khám phá theo thể loại',
  },
  videos: {
    eyebrow: 'MV cho phiên này',
    title: 'Video hợp mood này',
    subtitle: 'Chọn theo cảm xúc và gu nghe hiện tại',
    featuredLabel: 'Nổi bật',
    openVideo: 'Phát',
  },
  whyFits: {
    title: 'Vì sao hợp với cậu',
    items: [
      { id: 'mood', emoji: '🎭', text: 'Dựa trên cảm xúc hiện tại của cậu' },
      { id: 'replay', emoji: '🌙', text: 'Dựa trên thói quen nghe đêm khuya' },
      { id: 'genre', emoji: '🎵', text: 'Dựa trên gu K-pop gần đây' },
      { id: 'focus', emoji: '🎯', text: 'Dựa trên các phiên tập trung gần đây' },
    ],
  },
  library: {
    title: 'Thư viện của cậu',
    open: 'Mở thư viện',
    liked: 'Đã thích',
    playlists: 'Playlist',
    songs: 'Bài hát',
    thisWeek: 'Tuần này',
    songsUnit: 'bài',
  },
  rightColumn: {
    eyebrow: 'Gợi ý tiếp',
    title: 'Nên mở tiếp',
    all: 'Tất cả',
    reasons: ['Hợp cảm xúc.', 'Hợp gu nghe.', 'AI chọn.'],
  },
} as const

export const appShellCopy = {
  pageMeta: {
    '/bangDieuKhien': { eyebrow: 'Trang chủ', title: 'Không gian nghe của cậu' },
    '/nhanDienCamXuc': { eyebrow: 'Cảm xúc AI', title: 'Đọc cảm xúc hiện tại' },
    '/goiY': { eyebrow: 'Gợi ý', title: 'Playlist hợp với cảm xúc này' },
    '/thuVien': { eyebrow: 'Thư viện', title: 'Kho nhạc của cậu' },
    '/dangPhat': { eyebrow: 'Đang phát', title: 'Bài đang ở trung tâm phiên nghe' },
    '/lichSu': { eyebrow: 'Lịch sử', title: 'Lịch sử nghe và cảm xúc' },
    '/phanTich': { eyebrow: 'Phân tích', title: 'Nhịp nghe và xu hướng cảm xúc' },
    '/caiDat': { eyebrow: 'Cài đặt', title: 'Tinh chỉnh trải nghiệm nghe' },
  },
  fallbackPage: { eyebrow: 'MoodSync AI', title: 'Âm nhạc bắt đầu từ cảm xúc' },
  searchPlaceholder: 'Tìm bài hát, nghệ sĩ, cảm xúc',
  premium: {
    eyebrow: 'Premium',
    title: 'Mở rộng trải nghiệm MoodSync AI',
    description: 'Playlist thích ứng, phân tích sâu hơn, nhận diện cảm xúc nâng cao và trợ lý AI giàu ngữ cảnh hơn.',
    cta: 'Khám phá Premium',
    moodAi: 'Mood AI',
  },
  sidebar: {
    brandEyebrow: 'nhạc theo cảm xúc',
    moodTitle: 'Tâm trạng',
    syncLabel: 'AI đồng bộ',
    groups: {
      listen: 'Nghe nhạc',
      insight: 'Cảm xúc AI',
      system: 'Cài đặt',
    },
    navLabels: {
      home: 'Trang chủ',
      dashboard: 'Trang chính',
      nowPlaying: 'Đang phát',
      recommendations: 'Gợi ý',
      library: 'Thư viện',
      emotionDetection: 'Nhận diện cảm xúc',
      history: 'Lịch sử',
      analytics: 'Phân tích',
      settings: 'Cài đặt',
    },
  },
} as const

export const assistantPanelCopy = {
  eyebrow: 'Trợ lý AI',
  title: 'Mood Copilot',
  description: 'Phát nhạc, mở trang, đọc cảm xúc, xem gu nghe và giải thích gợi ý ngay trong app.',
  currentContext: 'Ngữ cảnh hiện tại',
  routeLabel: 'Trang',
  moodLabel: 'Cảm xúc',
  inputPlaceholder: 'Ví dụ: phát gì đó dịu lại',
  moodCardLabel: 'Cảm xúc',
  topGenreLabel: 'Thể loại chính',
  fastActionLabel: 'Tác vụ nhanh',
  ready: 'Sẵn sàng',
  quickActions: {
    voice: 'Voice AI',
    taste: 'Gu nghe',
    moodAction: 'Hành động nhanh',
  },
} as const
